apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: noxium-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: noxium-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
